### ISSUE TITLE
好像有防止GFW RST 的方法了

### ISSUE THREAD

**Issue by PantherJohn** [googlehosts/hosts#131]
看这里
https://github.com/seclab-ucr/INTANG/blob/master/README.md

**Comment by 123ysys** [comment]
坐等大佬研究。

**Comment by lrinQVQ** [comment]
2333有趣

**Comment by yalong1221** [comment]
``The logs can be found in /var/log/intangd.log
[aaron@localhost INTANG]$ sudo cat /var/log/intangd.log
1510406002.774565 [INFO] Previous version 0, current version 7
1510406002.774604 [INFO] Deleting redis DB due to version update.
1510406002.774628 [WARNING] Failed to delete redis db. errno: 2
1510406002.774724 [INFO] Starting redis server.
1510406003.342409 [INFO] Building sync connection with redis server.
1510406003.342603 [INFO] Sync connection built successfully.
1510406003.342705 [INFO] Loading historical results from redis.
1510406003.342755 [INFO] Connecting to TCP DNS server.
1510406003.342806 [INFO] Loading TTL from redis.
1510406003.342871 [INFO] Async connection built successfully.
1510406003.489426 [INFO] Connected to TCP DNS server.
1510406019.506883 [ERROR] Send keep alive packet failed. errno: 32
1510406019.507079 [INFO] Connecting to TCP DNS server.
1510406019.574953 [INFO] Connected to TCP DNS server.
[aaron@localhost INTANG]$ sudo cat /var/log/intangd.log
1510406002.774565 [INFO] Previous version 0, current version 7
1510406002.774604 [INFO] Deleting redis DB due to version update.
1510406002.774628 [WARNING] Failed to delete redis db. errno: 2
1510406002.774724 [INFO] Starting redis server.
1510406003.342409 [INFO] Building sync connection with redis server.
1510406003.342603 [INFO] Sync connection built successfully.
1510406003.342705 [INFO] Loading historical results from redis.
1510406003.342755 [INFO] Connecting to TCP DNS server.
1510406003.342806 [INFO] Loading TTL from redis.
1510406003.342871 [INFO] Async connection built successfully.
1510406003.489426 [INFO] Connected to TCP DNS server.
1510406019.506883 [ERROR] Send keep alive packet failed. errno: 32
1510406019.507079 [INFO] Connecting to TCP DNS server.
1510406019.574953 [INFO] Connected to TCP DNS server.
1510406066.963934 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_17066_25480141_20480_17
1510406067.198777 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_52361_2514420878_20480_6
[aaron@localhost INTANG]$ sudo cat /var/log/intangd.log
1510406002.774565 [INFO] Previous version 0, current version 7
1510406002.774604 [INFO] Deleting redis DB due to version update.
1510406002.774628 [WARNING] Failed to delete redis db. errno: 2
1510406002.774724 [INFO] Starting redis server.
1510406003.342409 [INFO] Building sync connection with redis server.
1510406003.342603 [INFO] Sync connection built successfully.
1510406003.342705 [INFO] Loading historical results from redis.
1510406003.342755 [INFO] Connecting to TCP DNS server.
1510406003.342806 [INFO] Loading TTL from redis.
1510406003.342871 [INFO] Async connection built successfully.
1510406003.489426 [INFO] Connected to TCP DNS server.
1510406019.506883 [ERROR] Send keep alive packet failed. errno: 32
1510406019.507079 [INFO] Connecting to TCP DNS server.
1510406019.574953 [INFO] Connected to TCP DNS server.
1510406066.963934 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_17066_25480141_20480_17
1510406067.198777 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_52361_2514420878_20480_6
[aaron@localhost INTANG]$ sudo cat /var/log/intangd.log
1510406002.774565 [INFO] Previous version 0, current version 7
1510406002.774604 [INFO] Deleting redis DB due to version update.
1510406002.774628 [WARNING] Failed to delete redis db. errno: 2
1510406002.774724 [INFO] Starting redis server.
1510406003.342409 [INFO] Building sync connection with redis server.
1510406003.342603 [INFO] Sync connection built successfully.
1510406003.342705 [INFO] Loading historical results from redis.
1510406003.342755 [INFO] Connecting to TCP DNS server.
1510406003.342806 [INFO] Loading TTL from redis.
1510406003.342871 [INFO] Async connection built successfully.
1510406003.489426 [INFO] Connected to TCP DNS server.
1510406019.506883 [ERROR] Send keep alive packet failed. errno: 32
1510406019.507079 [INFO] Connecting to TCP DNS server.
1510406019.574953 [INFO] Connected to TCP DNS server.
1510406066.963934 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_17066_25480141_20480_17
1510406067.198777 [INFO] [EVAL] STRATEGY FAILED 1. HTTP NO RESPONSE. 1845602496_52361_2514420878_20480_6
[aaron@localhost INTANG]$ Daemon exited unexpectedly. Signal 11 recved.

**Comment by yalong1221** [comment]
目前不可用,有bug,可以好好研究

**Comment by lifeidle** [comment]
盼星星

**Comment by lrinQVQ** [comment]
2333顺便在我这里ipv6(非教育网)也出现了SNI RST的情况

**Comment by 123ysys** [comment]
完蛋了。

**Comment by WeihuaGu** [comment]
@yalong1221 是写入redis数据库出错了吗

**Comment by zyf2008Neptune** [comment]
不会跟以前的“西厢计划”一样吧。

**Comment by lrinQVQ** [comment]
能成功呢最好233不能成功也只能说是他们尽力而为了

**Comment by PantherJohn** [comment]
@zyf2008Neptune 还真是

**Comment by PantherJohn** [comment]
“There are also some recent research projects called Refraction Networking aiming at evading IP-blocking.”

**Comment by PantherJohn** [comment]
https://refraction.network

**Comment by PantherJohn** [comment]
都是美国人在做这 Freedom is not free.

**Comment by PantherJohn** [comment]
https://github.com/refraction-networking

**Comment by PantherJohn** [comment]
with support from the U.S. State Department's Bureau of Democracy, Human Rights, and Labor.

**Comment by triplekiller** [comment]
大神们现在都用什么翻墙？自己买vps搭梯子？

**Comment by lrinQVQ** [comment]
暂时依赖支持TLS 1.3 21的网站(Google有支持 和 Shadowsocks

**Comment by zhangzhengyi12** [comment]
校园网是不是对ss有独特的拦截机制，我用手机网络和家里ss都没问题，一用校园网就特别惨烈，能用也就是最多5分钟就GG 大部分情况连不上

**Comment by lrinQVQ** [comment]
昂理论上来说应该是教育网的出口对你的服务器所在地不友好

**Comment by lrinQVQ** [comment]
这个时候你就真的需要测试下sudo hping3 -S -p ss_port server_ip
是否大量丢包

**Comment by zhangzhengyi12** [comment]
基本上是Ping不通的，不过我的ec2服务器有时候更换一个IP可以正常连接一段时间

**Comment by lifeidle** [comment]
@lrinQVQ 
请问大神我应该如何设置浏览器才能在TLS 1.3 21的环境下上Google？

**Comment by lrinQVQ** [comment]
@lifeidle 2333我只在TG放了支持TLS 1.3 21的curl openssl 浏览器还未公布233

**Comment by JokerShao** [comment]
@lrinQVQ 半个月过去了，，事情还顺利吗？

**Comment by lifeidle** [comment]
@lrinQVQ 神辛苦了，我继续等！

**Comment by lrinQVQ** [comment]
2333还算顺利 吧

**Comment by PantherJohn** [comment]
要知道这里JS Chinatelecom google没一个ip能用怎么tls1.3...

**Comment by lrinQVQ** [comment]
嘛 ICMP是肯定不通的 目前你只能尝试TCP 443能通的IP 至少我已经有了2000个可用IP了咩 同Chinatelecom @PantherJohn

**Comment by TheBitterSeaShip** [comment]
quic

**Comment by SerCom-KC** [comment]
@TheBitterSeaShip 国内 UDP 环境太烂，并不是所有环境下都能愉快地 QUIC……

**Comment by yym0924** [comment]
就是通过改hosts上Google以后是不是就没戏了

**Comment by SerCom-KC** [comment]
@yym0924 并不，目前只是被 GFW 抓到了把柄而已。就像 hosts 翻墙必须得用 HTTPS 而非明文的 HTTP 一样，这次也只是因为某个（会产生明文信息的）漏洞被 GFW 利用，而又没有及时修补而已

**Comment by JokerShao** [comment]
从开会前到现在已经快两个月没用过google了，感觉好别扭啊，chrome都登出了。不知道什么时候再能用啊？@SerCom-KC

**Comment by SerCom-KC** [comment]
@JokerShao 按目前的开发进度表要求是 1 月左右要解决这个问题（以下省略免责声明若干字）

**Comment by JokerShao** [comment]
@SerCom-KC 了解啦，谢谢！

**Comment by roc1010kmt** [comment]
連接是英文的==話說rst是什麼意思？

**Comment by SerCom-KC** [comment]
@roc1010kmt 就是 RESET，（连接）重置的意思。
为什么使用 hosts 强调一定要用 https 的原因之一

**Comment by valarhiker** [comment]
为什么我改hosts死活登不上google.

**Comment by SerCom-KC** [comment]
@valarhiker https://github.com/googlehosts/hosts/wiki#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%B0%E7%8E%B0%E5%9C%A8%E9%83%BD%E8%BF%98%E4%B8%8A%E4%B8%8D%E4%BA%86-googletwitterfacebookonedrivedropbox-%E7%AD%89%E6%9C%8D%E5%8A%A1

**Comment by dalton-chiou** [comment]
tls 1.3 draft 28 通过？那么，接下来……
https://tools.ietf.org/html/draft-ietf-tls-tls13-28

**Comment by SerCom-KC** [comment]
@dalton-chiou 如果我没有理解错的话，TLS 1.3允许被降级至1.2，这一点还是能被GFW利用。
cc @lrinQVQ

**Comment by Developers13** [comment]
Daedalus

**Comment by hallochina** [comment]
不折腾了，走付费v.pn吧，https://vpnchina.zdhweb.com

**Comment by draftingkitty** [comment]
没理解错的话client hello的时候浏览器会告诉服务器自己所支持的协议， 如果浏览器支持1.3, 服务器也支持1.3的情况下是不能降到1.2的。降级好像只是在一方不支持1.3的时候才有。1.3似乎有防止降级的机制

**Comment by beyondgfw** [comment]
@draftingkitty OpenSSL没有默认启用

**Comment by Crystal-RainSlide** [comment]
有就好~
但…
1. 怎么看其他SSL程序的情况
 比如，ShadowSocks 还用了 libsodium ，不知是否影响（libcrypto 是 OpenSSL）
2. 得先等它们上 TLS 1.3

**Comment by draftingkitty** [comment]
@beyondgfw 最终版本是draft 28, 那里面没记错有抗降级的机制啊

**Comment by beyondgfw** [comment]
@draftingkitty 在正式发布之前openssl是不会支持的

**Comment by draftingkitty** [comment]
@beyondgfw 不是已经发布了吗
https://www.theregister.co.uk/2018/03/27/with_tls_13_signed_off_its_implementation_time/
. 但是现在好像boringssl，openssl他们支持的都只是draft?

**Comment by beyondgfw** [comment]
@draftingkitty 目前TLS1.3还才脱离草案没有进入RFC

**Comment by draftingkitty** [comment]
@beyondgfw akamai说今年春天开始执行1.3? 他们自己的blog上这么说的，他们是openssl吧？说起来6月份就算夏天了...

**Comment by beyondgfw** [comment]
@draftingkitty 233目前执行的大多都是23草案

**Comment by SerCom-KC** [comment]
Akamai 上的是草案版（用于测试）吧，类似 Cloudflare 目前也只是作为 BETA 功能而已，并不等同于正式上线？
而且他们肯定要对 TLS 库做修改以适配自己的系统吧……🤔

**Comment by draftingkitty** [comment]
https://blogs.akamai.com/2018/04/tls-13-this-spring.html
他们说的这个应该是最终版吧，'we are planning to deploy the final, published, version this Spring.'

**Comment by Just2co** [comment]
TLS1.3已经正式放出，Facebook已经默认启用，各位大佬有没有什么新想法应用在hosts上面？

**Comment by beyondgfw** [comment]
@Just2co #技术向说明 预计近期将会修复Google等网站的访问,原理示例:status.googlehosts.org (请开启TLS1.3 28草案)

**Comment by Crystal-RainSlide** [comment]
TLS 1.3 正式版已出。

**Comment by lrinQVQ** [comment]
服务器已经使用兼容所有草案的正式版了 客户端还未完全更新而已xd

**Comment by draftingkitty** [comment]
@IrinQVQ 说起客户端，我看报道boringssl有sni加密功能，是不是说用chrome比其他的安全一点？

**Comment by lrinQVQ** [comment]
@draftingkitty openssl目前也是是用boringssl源码
我给出的示例服务器就支持0 RTT

**Comment by draftingkitty** [comment]
@IrinQVQ 这个必须赞一个!
不过谷歌似乎有点磨蹭啊，有个ssllab可以测试服务器，google.com倒是早就1.3 draft 28了，其他的这么长时间没动静

**Comment by beyondgfw** [comment]
@draftingkitty 其实你要是在TG频道的话xd我们的这些东西早就公布出来了的

**Comment by beyondgfw** [comment]
目前的情况应该属于 SNI RST 而不是 TCP 层面的 RST 了。
先关掉了。
